- name: "Setup Redis container on 6379:6379"
  community.docker.docker_container:
    name: redis
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - name: paper

  register: redis_container

- name: Wait until Redis is available
  wait_for: port="6379" delay=6
  when: redis_container.changed
