---

- hosts: all
  become: true
  roles:
    - role: base
      tags:
        - base
    - role: docker
      tags:
        - docker
    - role: redis
      tags:
        - redis
    - role: db_postgres
        - db
    - role: papermerge
      tags:
        - papermerge
