version: 1
disable_existing_loggers: true

formatters:
  verbose:
    format: '%(asctime)s %(levelname)s %(name)s.%(funcName)s %(message)s'

handlers:
  console:
    level: DEBUG
    class: logging.StreamHandler
    formatter: verbose

root:
  level: DEBUG
  handlers: [ console ]
  propagate: no
  format: verbose

loggers:
  celery:
    level: DEBUG
    handlers: [ console ]
    propagate: no
    format: verbose
  papermerge.core:
    level: DEBUG
    handlers: [console]
    propagate: no
    format: verbose
