- name: "PostgreSQL"
  community.docker.docker_container:
    name: db
    image: bitnami/postgresql:16.1.0
    restart: true
    restart_policy: "unless-stopped"
    env:
      POSTGRESQL_USER: "{{ db_user }}"
      POSTGRESQL_PASSWORD: "{{ db_pass }}"
      POSTGRES_DATABASE: "{{ db_name }}"
      POSTGRESQL_POSTGRES_PASSWORD: "{{ db_postgres_pass }}"
    ports:
      - "{{ db_port }}:{{ db_port }}"
    networks:
      - name: paper
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  register: db_container

- name: Wait until PostgresSQL is available
  wait_for: port="{{db_port | int}}" delay=6
  when: db_container.changed
