- name: "MariaDB"
  community.docker.docker_container:
    name: db
    image: mariadb:11.2
    restart: true
    restart_policy: "unless-stopped"
    env:
      MYSQL_ROOT_PASSWORD: "{{ db_pass }}"
      MYSQL_DATABASE: "{{ db_name }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_pass }}"
    ports:
      - "{{ db_port }}:{{ db_port }}"
    networks:
      - name: paper
    volumes:
      - maria:/var/lib/mysql
  register: db_container

- name: Wait until MariaDB is available
  wait_for: port="{{db_port | int}}" delay=6
  when: db_container.changed
