- name: Create /etc/papermerge folder
  file:
    path: /etc/papermerge
    state: directory

- name: Copy logging.yml to remote
  copy:
    src: logging.yml
    dest: /etc/papermerge/logging.yml

- name: Copy settings to remote
  copy:
    src: settings.py
    dest: /etc/papermerge/settings.py

- name: Deploy web app
  community.docker.docker_container:
    name: web_app
    image: "{{ image }}"
    restart: true
    restart_policy: "unless-stopped"
    env:
      PAPERMERGE__SECURITY__SECRET_KEY: "{{ secret_key }}"
      PAPERMERGE__AUTH__PASSWORD: "{{ superuser_password }}"
      PAPERMERGE__AUTH__USERNAME: "{{ superuser_username }}"
      PAPERMERGE__DATABASE__URL: "{{ database_url }}"
      PAPERMERGE__DATABASE__POOL_SIZE: "30"
      PAPERMERGE__REDIS__URL: "{{ redis_url }}"
      PAPERMERGE__SEARCH__URL: "{{ search_url }}"
    volumes:
      - data:/db
      - media:/core_app/media
      - /etc/papermerge/logging.yml:/core_app/logging.yml
      - /etc/papermerge/settings.py:/core_app/config/settings.py
    links:
      - db
      - redis
      - solr
    networks:
      - name: paper
    ports:
      - "{{web_app_port}}:80"
    labels:
      traefik.enable: "true"
      traefik.http.routers.paper.rule: "Host(`{{ acme_domain }}`)"
      traefik.http.routers.paper.tls: "true"
      traefik.http.routers.paper.tls.certresolver: le

- name: Deploy {{ worker_count }} worker(s)
  community.docker.docker_container:
    name: worker{{ item }}
    image: "{{ image }}"
    restart: true
    restart_policy: "unless-stopped"
    command: worker
    volumes:
      - data:/db
      - media:/core_app/media
      - /etc/papermerge/logging.yml:/core_app/logging.yml
    links:
      - db
      - redis
      - solr
    networks:
      - name: paper
    env:
      PAPERMERGE__SECURITY__SECRET_KEY: "{{ secret_key }}"
      PAPERMERGE__AUTH__PASSWORD: "{{ superuser_password }}"
      PAPERMERGE__AUTH__USERNAME: "{{ superuser_username }}"
      PAPERMERGE__DATABASE__URL: "{{ database_url }}"
      PAPERMERGE__REDIS__URL: "{{ redis_url }}"
      PAPERMERGE__SEARCH__URL: "{{ search_url }}"
  with_sequence: count={{ worker_count }}
