- name: Deploy web app
  community.docker.docker_container:
    name: web_app
    image: "{{ image }}"
    env:
      PAPERMERGE__SECURITY__SECRET_KEY: "{{ secret_key }}"
      PAPERMERGE__AUTH__PASSWORD: "{{ superuser_password }}"
      PAPERMERGE__AUTH__USERNAME: "{{ superuser_username }}"
    ports:
      - 9400:80
