- name: Deploy web app
  community.docker.docker_container:
    name: web_app
    image: papermerge/papermerge:3.0a7
    env:
      PAPERMERGE__MAIN__SECRET_KEY: "{{ secret_key }}"
      DJANGO_SUPERUSER_PASSWORD: "{{ superuser_password }}"

