- name: Create /etc/papermerge folder
  file:
    path: /etc/papermerge
    state: directory

- name: Copy logging.yml to remote
  copy:
    src: logging.yml
    dest: /etc/papermerge/logging.yml

- name: Copy settings to remote
  copy:
    src: settings.py
    dest: /etc/papermerge/settings.py

- name: Set Common Env
  ansible.builtin.set_fact:
    common_env:
      PAPERMERGE__SECURITY__SECRET_KEY: "{{ secret_key }}"
      PAPERMERGE__AUTH__PASSWORD: "{{ superuser_password }}"
      PAPERMERGE__AUTH__USERNAME: "{{ superuser_username }}"
      PAPERMERGE__DATABASE__URL: "{{ database_url }}"
      PAPERMERGE__DATABASE__POOL_SIZE: "30"
      PAPERMERGE__REDIS__URL: "{{ redis_url }}"
      PAPERMERGE__SEARCH__URL: "{{ search_url }}"
      PAPERMERGE__OCR__DEFAULT_LANGUAGE: "{{ default_ocr_lang }}"

- name: Set Google Auth Env (default value)
  ansible.builtin.set_fact:
    google_auth_env: {}

- name: Set GitHub Auth Env (default valiue)
  ansible.builtin.set_fact:
    github_auth_env: {}

- name: Set LDAP Auth Env (default valiue)
  ansible.builtin.set_fact:
    ldap_auth_env: {}

- name: Set Google Auth Env
  ansible.builtin.set_fact:
    google_auth_env:
      PAPERMERGE__AUTH__GOOGLE_CLIENT_SECRET: "{{ google_client_secret }}"
      PAPERMERGE__AUTH__GOOGLE_CLIENT_ID: "{{ google_client_id }}"
      PAPERMERGE__AUTH__GOOGLE_AUTHORIZE_URL: "{{ google_authorize_url }}"
      PAPERMERGE__AUTH__GOOGLE_REDIRECT_URI: "{{ google_redirect_uri }}"
  when: "'google' in auth_mode"

- name: Set GitHub Auth Env
  ansible.builtin.set_fact:
    github_auth_env:
      PAPERMERGE__AUTH__GITHUB_CLIENT_SECRET: "{{ github_client_secret }}"
      PAPERMERGE__AUTH__GITHUB_CLIENT_ID: "{{ github_client_id }}"
      PAPERMERGE__AUTH__GITHUB_AUTHORIZE_URL: "{{ github_authorize_url }}"
      PAPERMERGE__AUTH__GITHUB_REDIRECT_URI: "{{ github_redirect_uri }}"
  when: "'github' in auth_mode"

- name: Set LDAP Auth Env
  ansible.builtin.set_fact:
    ldap_auth_env:
      PAPERMERGE__AUTH__LDAP_URL: "{{ ldap_url }}"
      PAPERMERGE__AUTH__LDAP_USER_DN_FORMAT: "{{ ldap_user_dn_format }}"
  when: "'ldap' in auth_mode"

- name: Deploy web app {{ image }}
  community.docker.docker_container:
    name: web_app
    image: "{{ image }}"
    restart: true
    restart_policy: "unless-stopped"
    env: "{{ common_env | combine(github_auth_env, google_auth_env, ldap_auth_env) }}"

    volumes:
      - data:/db
      - media:/core_app/media
      - /etc/papermerge/logging.yml:/core_app/logging.yml
      - /etc/papermerge/settings.py:/core_app/config/settings.py
    links:
      - db
      - redis
      - solr
    networks:
      - name: paper
    labels:
      traefik.enable: "true"
      traefik.http.routers.paper.rule: "Host(`{{ acme_domain }}`)"
      traefik.http.routers.paper.tls: "true"
      traefik.http.routers.paper.tls.certresolver: le

- name: Deploy {{ worker_count }} worker(s)
  community.docker.docker_container:
    name: worker{{ item }}
    image: "{{ image }}"
    restart: true
    restart_policy: "unless-stopped"
    command: worker
    volumes:
      - data:/db
      - media:/core_app/media
      - /etc/papermerge/logging.yml:/core_app/logging.yml
    links:
      - db
      - redis
      - solr
    networks:
      - name: paper
    env:
      PAPERMERGE__SECURITY__SECRET_KEY: "{{ secret_key }}"
      PAPERMERGE__AUTH__PASSWORD: "{{ superuser_password }}"
      PAPERMERGE__AUTH__USERNAME: "{{ superuser_username }}"
      PAPERMERGE__DATABASE__URL: "{{ database_url }}"
      PAPERMERGE__REDIS__URL: "{{ redis_url }}"
      PAPERMERGE__SEARCH__URL: "{{ search_url }}"
      PAPERMERGE__WORKER__ARGS: "-c {{child_processes_count}}"
  with_sequence: count={{ worker_count }}
