- name: Solr
  community.docker.docker_container:
    name: solr
    image: "{{ solr_image }}"
    restart: true
    restart_policy: "unless-stopped"
    ports:
      - "{{ solr_port }}:{{ solr_port }}"
    volumes:
      - solr_data:/var/solr
    networks:
      - name: paper
    command:
      - solr-precreate
      - "{{ index_name }}"
  register: solr_container

- name: Wait until Solr is available
  wait_for: port="{{solr_port | int}}" delay=6
  when: solr_container.changed
